services:

  web-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shop_web_api
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=Shop;Username=postgres;Password=12345
    depends_on:
      - db
    networks:
      - dev
    restart: always

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: shop_frontend
      ports:
        - "80:80"
      environment:
        - REACT_APP_API_URL=http://web-api:5000
      networks:
      - dev
      restart: always

  db:
    image: postgres:latest
    container_name: shop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dev
    restart: always
  
volumes:
  postgres_data:

networks:
  dev:
    driver: bridge
